services:
  - type: web
    name: object-recognition
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /health
    healthCheckTimeout: 60
    buildCommand: docker build -t object-recognition .
    startCommand: docker run -p $PORT:10000 -e PORT=$PORT -e DEBUG=true object-recognition
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: YOLO_MODEL
        value: yolov8n.pt
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: true
    scaling:
      minInstances: 1
      maxInstances: 1
    autoDeploy: true 