services:
  - type: web
    name: object-recognition
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /
    buildCommand: docker build -t object-recognition .
    startCommand: docker run -p $PORT:10000 object-recognition
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: YOLO_MODEL
        value: yolov8n.pt
    scaling:
      minInstances: 1
      maxInstances: 1
    autoDeploy: true 